micronaut:
    application:
        name: account-control
grpc:
    server:
        port: 8082
kafka:
    producers:
        debit-client:
            value:
                serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer

# Uncomment to enable service discovery with Consul
#consul:
#    client:
#        registration:
#            enabled: true
#        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"